"""FMD Engine Worker — runs pipeline loads independently of the dashboard server.

This is the detached execution entry point for durable, resumable pipeline runs.
It survives dashboard server restarts because it runs as a separate process.

Logging: console only (StreamHandler). When spawned by the API, stdout/stderr
are redirected to a per-run log file. Do NOT add a FileHandler here — the API
owns the log file to avoid double-write and Windows file-handle conflicts.

Usage:
    # New run (API-spawned — run_id pre-generated):
    python -m engine.worker --run-id <uuid> --layers landing bronze silver

    # Resume interrupted run:
    python -m engine.worker --resume <run_id>

    # Direct invocation (generates own run_id):
    python -m engine.worker --layers landing bronze silver --triggered-by manual
"""

import argparse
import logging
import os
import sys

# Ensure project root is on sys.path so engine.* and dashboard.* imports work
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

log = logging.getLogger("fmd.worker")


def main():
    parser = argparse.ArgumentParser(description="FMD Engine Worker")
    parser.add_argument("--run-id", help="Explicit run ID (pre-generated by API)")
    parser.add_argument("--resume", metavar="RUN_ID", help="Resume an interrupted run")
    parser.add_argument("--layers", nargs="*", help="Layers to run (landing bronze silver)")
    parser.add_argument("--entity-ids", nargs="*", type=int, help="Specific entity IDs")
    parser.add_argument("--triggered-by", default="worker")
    args = parser.parse_args()

    # Console-only logging (API redirects stdout to per-run log file)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        handlers=[logging.StreamHandler()],
    )

    pid = os.getpid()
    log.info("Worker PID %d starting", pid)

    from engine.config import load_config
    from engine.orchestrator import LoadOrchestrator

    config = load_config()
    engine = LoadOrchestrator(config)

    if args.resume:
        # Resume: recover original run shape from engine_runs
        run_meta = engine._cpdb_query(
            "SELECT Layers, EntityFilter FROM engine_runs WHERE RunId = ?", (args.resume,)
        )
        run_row = run_meta[0] if run_meta else {}

        layers = args.layers
        if not layers and run_row.get("Layers"):
            layers = [l.strip() for l in run_row["Layers"].split(",") if l.strip()]
            log.info("Resume: recovered original layers from engine_runs: %s", layers)

        # Recover entity_ids filter (if the original run was scoped)
        entity_ids = args.entity_ids
        if not entity_ids and run_row.get("EntityFilter"):
            try:
                entity_ids = [int(x) for x in run_row["EntityFilter"].split(",") if x.strip()]
                log.info("Resume: recovered %d entity IDs from engine_runs.EntityFilter", len(entity_ids))
            except (ValueError, TypeError):
                pass

        # Write PID and mark InProgress
        engine._cpdb_execute(
            "UPDATE engine_runs SET WorkerPid = ?, Status = 'InProgress' WHERE RunId = ?",
            (pid, args.resume),
        )

        results = engine.run(
            resume_run_id=args.resume,
            layers=layers,
            entity_ids=entity_ids,
            triggered_by=args.triggered_by,
        )
    else:
        # New run
        # Write PID after run() sets up the engine_runs row
        results = engine.run(
            run_id=args.run_id,
            layers=args.layers,
            entity_ids=args.entity_ids,
            triggered_by=args.triggered_by,
        )
        # Update PID (run_id may have been generated inside run())
        effective_run_id = args.run_id or engine.current_run_id
        if effective_run_id:
            engine._cpdb_execute(
                "UPDATE engine_runs SET WorkerPid = ? WHERE RunId = ?",
                (pid, effective_run_id),
            )

    # Summary
    if isinstance(results, list):
        s = sum(1 for r in results if r.status == "succeeded")
        f = sum(1 for r in results if r.status == "failed")
        sk = sum(1 for r in results if r.status == "skipped")
        log.info("Run complete: %d succeeded, %d failed, %d skipped, %d total",
                 s, f, sk, len(results))
    else:
        log.info("Plan returned (not a run result)")


if __name__ == "__main__":
    main()
