"""FMD Engine Worker — runs pipeline loads independently of the dashboard server.

This is the detached execution entry point for durable, resumable pipeline runs.
It survives dashboard server restarts because it runs as a separate process.

Logging: console only (StreamHandler). When spawned by the API, stdout/stderr
are redirected to a per-run log file. Do NOT add a FileHandler here — the API
owns the log file to avoid double-write and Windows file-handle conflicts.

Usage:
    # New run (API-spawned — run_id pre-generated):
    python -m engine.worker --run-id <uuid> --layers landing bronze silver

    # Bulk snapshot (fast parallel full-load, no watermarks/retries):
    python -m engine.worker --run-id <uuid> --bulk --workers 8

    # Resume interrupted run:
    python -m engine.worker --resume <run_id>

    # Direct invocation (generates own run_id):
    python -m engine.worker --layers landing bronze silver --triggered-by manual
"""

import argparse
import logging
import os
import sys

# Ensure project root is on sys.path so engine.* and dashboard.* imports work
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

log = logging.getLogger("fmd.worker")


def main():
    parser = argparse.ArgumentParser(description="FMD Engine Worker")
    parser.add_argument("--run-id", help="Explicit run ID (pre-generated by API)")
    parser.add_argument("--resume", metavar="RUN_ID", help="Resume an interrupted run")
    parser.add_argument("--layers", nargs="*", help="Layers to run (landing bronze silver)")
    parser.add_argument("--entity-ids", nargs="*", type=int, help="Specific entity IDs")
    parser.add_argument("--triggered-by", default="worker")
    parser.add_argument("--bulk", action="store_true",
                        help="Bulk snapshot mode: parallel full-load, no watermarks/retries")
    parser.add_argument("--workers", type=int, default=8,
                        help="Max parallel workers for bulk mode (default: 8)")
    parser.add_argument("--force-full-refresh", action="store_true",
                        help="For scoped proof/backfill runs, ignore landing watermarks for this run only")
    args = parser.parse_args()

    # Console-only logging (API redirects stdout to per-run log file)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        handlers=[logging.StreamHandler()],
    )
    logging.getLogger("azure.core.pipeline.policies.http_logging_policy").setLevel(logging.WARNING)

    pid = os.getpid()
    log.info("Worker PID %d starting", pid)

    from engine.config import load_config
    from engine.orchestrator import LoadOrchestrator

    config = load_config()
    engine = LoadOrchestrator(config)

    if args.bulk:
        # ── Bulk Snapshot Mode ─────────────────────────────────────────
        import uuid as _uuid
        from engine.auth import TokenProvider
        from engine.connections import SourceConnection
        from engine.loader import OneLakeLoader
        from engine.logging_db import AuditLogger
        from engine.bulk_snapshot import BulkSnapshot

        run_id = args.run_id or str(_uuid.uuid4())
        tokens = TokenProvider(config)
        source_conn = SourceConnection(config)
        loader = OneLakeLoader(config, tokens)
        audit = AuditLogger()

        # Fetch worklist (reuse orchestrator's query)
        entities = engine.get_worklist(args.entity_ids)
        log.info("Bulk snapshot: %d entities, %d workers", len(entities), args.workers)

        # Log run start
        audit.log_run_start(run_id, "bulk", len(entities), ["landing"], args.triggered_by)

        # Update PID on pre-created engine_runs row
        engine._cpdb_execute(
            "UPDATE engine_runs SET WorkerPid = ?, CurrentLayer = 'landing' WHERE RunId = ?",
            (pid, run_id),
        )

        snap = BulkSnapshot(config, source_conn, loader, audit)
        results = snap.run(run_id, entities, max_workers=args.workers)

        # Log run end
        audit.log_run_end(run_id, results)

    elif args.resume:
        # Resume: recover original run shape from engine_runs
        run_meta = engine._cpdb_query(
            "SELECT Layers, EntityFilter, Mode FROM engine_runs WHERE RunId = ?", (args.resume,)
        )
        run_row = run_meta[0] if run_meta else {}

        layers = args.layers
        if not layers and run_row.get("Layers"):
            layers = [l.strip() for l in run_row["Layers"].split(",") if l.strip()]
            log.info("Resume: recovered original layers from engine_runs: %s", layers)

        # Recover entity_ids filter (if the original run was scoped)
        entity_ids = args.entity_ids
        if not entity_ids and run_row.get("EntityFilter"):
            try:
                entity_ids = [int(x) for x in run_row["EntityFilter"].split(",") if x.strip()]
                log.info("Resume: recovered %d entity IDs from engine_runs.EntityFilter", len(entity_ids))
            except (ValueError, TypeError):
                pass

        # Write PID and mark InProgress
        engine._cpdb_execute(
            "UPDATE engine_runs SET WorkerPid = ?, Status = 'InProgress' WHERE RunId = ?",
            (pid, args.resume),
        )

        original_mode = (run_row.get("Mode") or "").lower()

        if original_mode == "bulk":
            # ── Resume a bulk run via BulkSnapshot (fast parallel path) ──
            from engine.auth import TokenProvider
            from engine.connections import SourceConnection
            from engine.loader import OneLakeLoader
            from engine.logging_db import AuditLogger
            from engine.bulk_snapshot import BulkSnapshot

            tokens = TokenProvider(config)
            source_conn = SourceConnection(config)
            loader = OneLakeLoader(config, tokens)
            audit = AuditLogger()

            # Get full worklist, then filter out already-succeeded
            all_entities = engine.get_worklist(entity_ids)
            completed_ids = set()
            completed_rows = engine._cpdb_query(
                "SELECT DISTINCT EntityId FROM engine_task_log "
                "WHERE RunId = ? AND LOWER(Status) = 'succeeded'",
                (args.resume,),
            )
            for r in completed_rows:
                completed_ids.add(int(r["EntityId"]))

            remaining = [e for e in all_entities if e.id not in completed_ids]
            log.info(
                "Bulk resume: %d total, %d already succeeded, %d remaining",
                len(all_entities), len(completed_ids), len(remaining),
            )

            workers = args.workers or 16
            snap = BulkSnapshot(config, source_conn, loader, audit)
            results = snap.run(args.resume, remaining, max_workers=workers)

            audit.log_run_end(args.resume, results)
        else:
            # Standard orchestrator resume
            results = engine.run(
                resume_run_id=args.resume,
                layers=layers,
                entity_ids=entity_ids,
                triggered_by=args.triggered_by,
            )
    else:
        # New run
        # Write PID after run() sets up the engine_runs row
        results = engine.run(
            run_id=args.run_id,
            layers=args.layers,
            entity_ids=args.entity_ids,
            triggered_by=args.triggered_by,
            force_full_refresh=args.force_full_refresh,
        )
        # Update PID (run_id may have been generated inside run())
        effective_run_id = args.run_id or engine.current_run_id
        if effective_run_id:
            engine._cpdb_execute(
                "UPDATE engine_runs SET WorkerPid = ? WHERE RunId = ?",
                (pid, effective_run_id),
            )

    # Summary
    if isinstance(results, list):
        s = sum(1 for r in results if r.status == "succeeded")
        f = sum(1 for r in results if r.status == "failed")
        sk = sum(1 for r in results if r.status == "skipped")
        log.info("Run complete: %d succeeded, %d failed, %d skipped, %d total",
                 s, f, sk, len(results))
    else:
        log.info("Plan returned (not a run result)")


if __name__ == "__main__":
    main()
