import { test, expect } from '@playwright/test';
import {
  collectConsoleErrors, expectRealValue, parseDisplayNumber,
  waitForStable, screenshot, assertNoOverflow,
  ADVERSARIAL_INPUTS, BUTTON_DENYLIST,
} from './test-helpers';

/**
 * Comprehensive tests for: /gold/intake
 * Component: Gold Intake
 * Source: dashboard/app/src/App.tsx
 *
 *
 * Generated by MRI Test Generator
 */

test.describe('Page: /gold/intake', () => {

  async function navigateToPage(page: import('@playwright/test').Page) {
    await page.goto('/gold/intake');
    await waitForStable(page);
  }

  // ════════════════════════════════════════════════════════════
  // SECTION 1: Core Rendering
  // ════════════════════════════════════════════════════════════

  test('loads without console errors', async ({ page }) => {
    const errors = collectConsoleErrors(page);
    await navigateToPage(page);
    await expect(page.locator('body')).toBeVisible();
    expect(errors).toHaveLength(0);
  });

  test('renders meaningful content (not blank screen)', async ({ page }) => {
    await navigateToPage(page);
    const bodyHTML = await page.locator('body').innerHTML();
    expect(bodyHTML.trim().length).toBeGreaterThan(100);
    const text = (await page.locator('body').textContent()) || '';
    expect(text.toLowerCase()).not.toContain('cannot read properties');
    expect(text.toLowerCase()).not.toContain('is not defined');
    expect(text.toLowerCase()).not.toContain('unexpected token');
    expect(text.toLowerCase()).not.toContain('uncaught error');
    expect(text.toLowerCase()).not.toContain('chunk load error');
  });

  // ════════════════════════════════════════════════════════════
  // SECTION 5: Interactive Element Stress Testing
  // ════════════════════════════════════════════════════════════

  test('all safe buttons are clickable without crash', async ({ page }) => {
    const errors = collectConsoleErrors(page);
    await navigateToPage(page);
    const buttons = page.locator('button:visible');
    const count = await buttons.count();
    for (let i = 0; i < count; i++) {
      const btn = buttons.nth(i);
      const text = (await btn.textContent() || '').trim();
      const ariaLabel = (await btn.getAttribute('aria-label')) || '';
      const combined = `${text} ${ariaLabel}`;
      if (BUTTON_DENYLIST.test(combined)) continue;
      if (await btn.isDisabled()) continue;
      try {
        await btn.click({ timeout: 3000 });
        await page.waitForTimeout(300);
      } catch { /* navigated or dialog opened */ }
      await expect(page.locator('body')).toBeVisible();
      if (!page.url().includes('/gold/intake')) {
        await page.goto('/gold/intake');
        await waitForStable(page);
      }
    }
  });

  test('all visible inputs accept text without error', async ({ page }) => {
    await navigateToPage(page);
    const inputs = page.locator(
      'input[type="text"]:visible, input[type="search"]:visible, '
      + 'input:not([type]):visible, textarea:visible'
    );
    const count = await inputs.count();
    for (let i = 0; i < count; i++) {
      const input = inputs.nth(i);
      if (await input.isEditable()) {
        await input.fill('test value');
        const value = await input.inputValue();
        expect(value).toBeTruthy();
      }
    }
  });

  test('dropdowns and selects are interactive', async ({ page }) => {
    await navigateToPage(page);
    const selects = page.locator('select:visible');
    const selectCount = await selects.count();
    for (let i = 0; i < selectCount; i++) {
      const select = selects.nth(i);
      const options = select.locator('option');
      if (await options.count() > 1) {
        const value = await options.nth(1).getAttribute('value');
        if (value) await select.selectOption(value);
      }
    }
    const triggers = page.locator('[role="combobox"]:visible, button[aria-haspopup="listbox"]:visible');
    const triggerCount = await triggers.count();
    for (let i = 0; i < Math.min(triggerCount, 5); i++) {
      try {
        await triggers.nth(i).click({ timeout: 2000 });
        await page.waitForTimeout(300);
        await page.keyboard.press('Escape');
      } catch { /* not interactable */ }
    }
  });

  test('checkboxes toggle without crash', async ({ page }) => {
    await navigateToPage(page);
    const checkboxes = page.locator('input[type="checkbox"]:visible, [role="checkbox"]:visible');
    const count = await checkboxes.count();
    for (let i = 0; i < Math.min(count, 10); i++) {
      const cb = checkboxes.nth(i);
      if (await cb.isEnabled()) {
        await cb.click();
        await page.waitForTimeout(200);
        await expect(page.locator('body')).toBeVisible();
        await cb.click();
      }
    }
  });

  // ════════════════════════════════════════════════════════════
  // SECTION 8: Responsive Layout
  // ════════════════════════════════════════════════════════════

  test('renders without crash at mobile width (375px)', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await navigateToPage(page);
    await expect(page.locator('body')).toBeVisible();
    const bodyHTML = await page.locator('body').innerHTML();
    expect(bodyHTML.trim().length).toBeGreaterThan(50);
    await screenshot(page, 'gold_intake-mobile');
  });

  test('renders without crash at ultrawide width (2560px)', async ({ page }) => {
    await page.setViewportSize({ width: 2560, height: 1440 });
    await navigateToPage(page);
    await expect(page.locator('body')).toBeVisible();
    const bodyHTML = await page.locator('body').innerHTML();
    expect(bodyHTML.trim().length).toBeGreaterThan(50);
    await screenshot(page, 'gold_intake-ultrawide');
  });

  // ════════════════════════════════════════════════════════════
  // SECTION 9: Accessibility
  // ════════════════════════════════════════════════════════════

  test('interactive elements are reachable by keyboard (Tab)', async ({ page }) => {
    await navigateToPage(page);
    const focusedElements: string[] = [];
    for (let i = 0; i < 30; i++) {
      await page.keyboard.press('Tab');
      const focused = await page.evaluate(() => {
        const el = document.activeElement;
        if (!el || el === document.body) return null;
        return `${el.tagName.toLowerCase()}.${el.className?.toString().slice(0, 30) || ''}`;
      });
      if (focused) focusedElements.push(focused);
    }
    expect(focusedElements.length).toBeGreaterThan(0);
  });

  test('buttons and links have accessible names', async ({ page }) => {
    await navigateToPage(page);
    const buttons = page.locator('button:visible');
    const btnCount = await buttons.count();
    for (let i = 0; i < btnCount; i++) {
      const btn = buttons.nth(i);
      const text = (await btn.textContent() || '').trim();
      const ariaLabel = await btn.getAttribute('aria-label');
      const title = await btn.getAttribute('title');
      const hasName = text.length > 0 || (ariaLabel || '').length > 0 || (title || '').length > 0;
      if (!hasName) {
        const hasSVG = await btn.locator('svg').count() > 0;
        if (hasSVG) {
          console.warn(`Icon button without accessible name at index ${i}`);
        }
      }
    }
    const images = page.locator('img:visible');
    const imgCount = await images.count();
    for (let i = 0; i < imgCount; i++) {
      const alt = await images.nth(i).getAttribute('alt');
      expect(alt, `Image at index ${i} should have alt attribute`).not.toBeNull();
    }
  });

  test('focus states are visible on interactive elements', async ({ page }) => {
    await navigateToPage(page);
    await page.keyboard.press('Tab');
    await page.keyboard.press('Tab');
    const hasFocusRing = await page.evaluate(() => {
      const el = document.activeElement as HTMLElement;
      if (!el || el === document.body) return true;
      const style = window.getComputedStyle(el);
      return style.outline !== 'none' ||
        style.outlineStyle !== 'none' ||
        style.boxShadow !== 'none' ||
        el.classList.contains('focus-visible') ||
        el.matches(':focus-visible');
    });
    if (!hasFocusRing) {
      console.warn('Active element may lack visible focus indicator');
    }
  });

  // ════════════════════════════════════════════════════════════
  // SECTION 11: Screenshot Capture
  // ════════════════════════════════════════════════════════════

  test('captures full-page screenshot', async ({ page }) => {
    await navigateToPage(page);
    await screenshot(page, 'gold_intake');
  });
});
