import { test, expect } from '@playwright/test';
import { collectConsoleErrors, waitForStable } from './test-helpers';

/**
 * Cross-page navigation tests.
 * Tests sequential navigation, browser back/forward, rapid navigation.
 * Generated by MRI Test Generator
 */

const routes = [
  '/',
  '/overview',
  '/alerts',
  '/sources-portal',
  '/catalog-portal',
  '/requests',
  '/help',
  '/matrix',
  '/engine',
  '/control',
  '/logs',
  '/errors',
  '/admin',
  '/flow',
  '/sources',
  '/blender',
  '/counts',
  '/journey',
  '/config',
  '/notebook-config',
  '/runner',
  '/validation',
  '/notebook-debug',
  '/live',
  '/settings',
  '/setup',
  '/sql-explorer',
  '/load-progress',
  '/profile',
  '/columns',
  '/microscope',
  '/sankey',
  '/replay',
  '/pulse',
  '/test-audit',
  '/test-swarm',
  '/mri',
  '/gold',
  '/gold/ledger',
  '/gold/clusters',
  '/gold/canonical',
  '/gold/specs',
  '/gold/validation',
  '/lineage',
  '/classification',
  '/catalog',
  '/impact',
  '/db-explorer',
  '/data-manager',
  '/load-center',
  '/load-mission-control',
  '/schema-validation',
  '/estate',
  '/labs/cleansing',
  '/labs/scd-audit',
  '/labs/gold-mlv',
  '/labs/dq-scorecard',
  '/vite-hmr',
  '/admin-gateway',
  '/admin-governance',
  '/business/business-alerts',
  '/business/business-catalog',
  '/business/business-help',
  '/business/business-requests',
  '/business/business-sources',
  '/business/dataset-detail',
  '/business-overview',
  '/cleansing-rule-editor',
  '/column-evolution',
  '/config-manager',
  '/control-plane',
  '/database-explorer',
  '/data-blender',
  '/data-catalog',
  '/data-classification',
  '/data-estate',
  '/data-journey',
  '/data-lineage',
  '/data-microscope',
  '/data-profiler',
  '/dq-scorecard',
  '/engine-control',
  '/environment-setup',
  '/error-intelligence',
  '/execution-log',
  '/execution-matrix',
  '/executive-dashboard',
  '/flow-explorer',
  '/gold/gold-canonical',
  '/gold/gold-clusters',
  '/gold/gold-ledger',
  '/gold/gold-specs',
  '/gold/gold-validation',
  '/gold-mlv-manager',
  '/impact-analysis',
  '/impact-pulse',
  '/live-monitor',
  '/m-r-i',
  '/pipeline-matrix',
  '/pipeline-monitor',
  '/pipeline-runner',
  '/record-counts',
  '/sankey-flow',
  '/scd-audit',
  '/source-manager',
  '/transformation-replay',
  '/validation-checklist',
  '/not-found',
];

test.describe('Cross-page navigation', () => {

  test('navigates through all routes without crash', async ({ page }) => {
    const errors = collectConsoleErrors(page);
    for (const route of routes) {
      await page.goto(route);
      await page.waitForLoadState('domcontentloaded');
      await expect(page.locator('body')).toBeVisible();
      const html = await page.locator('body').innerHTML();
      expect(html.trim().length).toBeGreaterThan(10);
    }
  });

  test('browser back/forward works across pages', async ({ page }) => {
    await page.goto('/');
    await waitForStable(page);
    await page.goto('/overview');
    await waitForStable(page);
    await page.goto('/alerts');
    await waitForStable(page);
    await page.goBack();
    await waitForStable(page);
    expect(page.url()).toContain('/overview');
    await page.goBack();
    await waitForStable(page);
    expect(page.url()).toContain('/');
    await page.goForward();
    await waitForStable(page);
    expect(page.url()).toContain('/overview');
  });

  test('rapid navigation between pages does not crash', async ({ page }) => {
    const subset = routes.slice(0, 10);
    for (const route of subset) {
      page.goto(route).catch(() => {});
      await page.waitForTimeout(200);
    }
    await waitForStable(page);
    await expect(page.locator('body')).toBeVisible();
  });
});
