import { test, expect } from '@playwright/test';
import {
  collectConsoleErrors, expectRealValue, parseDisplayNumber,
  waitForStable, screenshot, assertNoOverflow,
  ADVERSARIAL_INPUTS, BUTTON_DENYLIST,
} from './test-helpers';

/**
 * Comprehensive tests for: /cleansing-rule-editor
 * Component: CleansingRuleEditor
 * Source: dashboard/app/src/pages/CleansingRuleEditor.tsx
 *
 *
 * Generated by MRI Test Generator
 */

test.describe('Page: /cleansing-rule-editor', () => {

  async function navigateToPage(page: import('@playwright/test').Page) {
    await page.goto('/cleansing-rule-editor');
    await waitForStable(page);
  }

  // ════════════════════════════════════════════════════════════
  // SECTION 1: Core Rendering
  // ════════════════════════════════════════════════════════════

  test('loads without console errors', async ({ page }) => {
    const errors = collectConsoleErrors(page);
    await navigateToPage(page);
    await expect(page.locator('body')).toBeVisible();
    expect(errors).toHaveLength(0);
  });

  test('renders meaningful content (not blank screen)', async ({ page }) => {
    await navigateToPage(page);
    const bodyHTML = await page.locator('body').innerHTML();
    expect(bodyHTML.trim().length).toBeGreaterThan(100);
    const text = (await page.locator('body').textContent()) || '';
    expect(text.toLowerCase()).not.toContain('cannot read properties');
    expect(text.toLowerCase()).not.toContain('is not defined');
    expect(text.toLowerCase()).not.toContain('unexpected token');
    expect(text.toLowerCase()).not.toContain('uncaught error');
    expect(text.toLowerCase()).not.toContain('chunk load error');
  });

  test('shows coming soon indicator', async ({ page }) => {
    await navigateToPage(page);
    const body = (await page.locator('body').textContent()) || '';
    expect(body.toLowerCase()).toMatch(/coming soon|under construction|not.*implemented/i);
  });

  test('captures screenshot', async ({ page }) => {
    await navigateToPage(page);
    await screenshot(page, 'cleansing_rule_editor');
  });
});
