import { test, expect } from '@playwright/test';

/**
 * Comprehensive API endpoint tests.
 * Tests status codes, JSON validity, response shape, error handling, timing.
 * Generated by MRI Test Generator
 */

test.describe('API: GET endpoints — full validation', () => {

  test('GET /api/things returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/things');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/health returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/health');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/admin/config returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/admin/config');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/fabric/workspaces returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/fabric/workspaces');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/fabric/connections returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/fabric/connections');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/fabric/security-groups returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/fabric/security-groups');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/setup/current-config returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/setup/current-config');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/alerts returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/alerts');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/classification/status returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/classification/status');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/classification/summary returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/classification/summary');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/classification/data returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/classification/data');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/config-manager returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/config-manager');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/config-manager/references returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/config-manager/references');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/notebook-config returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/notebook-config');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/control-plane returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/control-plane');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/connections returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/connections');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/datasources returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/datasources');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/source-config returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/source-config');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/entities returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/entities');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/execution-matrix returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/execution-matrix');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/record-counts returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/record-counts');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sources returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sources');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/blender/tables returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/blender/tables');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/blender/endpoints returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/blender/endpoints');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/lakehouse-counts returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/lakehouse-counts');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/purview/status returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/purview/status');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/purview/search returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/purview/search');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/blender/profile returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/blender/profile');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/blender/sample returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/blender/sample');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/schema returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/schema');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/data-manager/tables returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/data-manager/tables');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/db-explorer/tables returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/db-explorer/tables');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/engine/status returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/engine/status');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/engine/plan returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/engine/plan');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/engine/logs returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/engine/logs');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/engine/health returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/engine/health');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/engine/metrics returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/engine/metrics');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/engine/runs returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/engine/runs');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/engine/validation returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/engine/validation');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/engine/settings returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/engine/settings');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/engine/entities returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/engine/entities');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/entity-digest returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/entity-digest');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/entity-digest/build returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/entity-digest/build');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/entities/cascade-impact returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/entities/cascade-impact');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/glossary returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/glossary');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/gold/domains returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/gold/domains');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/load-center/status returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/load-center/status');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/load-center/source-detail returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/load-center/source-detail');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/load-center/run-status returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/load-center/run-status');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/microscope returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/microscope');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/microscope/pks returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/microscope/pks');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/live-monitor returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/live-monitor');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/copy-executions returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/copy-executions');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/notebook-executions returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/notebook-executions');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/error-intelligence returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/error-intelligence');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/stats returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/stats');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/load-progress returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/load-progress');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/executive returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/executive');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/journey returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/journey');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/mri/runs returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/mri/runs');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/mri/status returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/mri/status');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/mri/baselines returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/mri/baselines');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/notebook-debug/notebooks returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/notebook-debug/notebooks');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/notebook-debug/entities returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/notebook-debug/entities');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/notebook-debug/job-status returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/notebook-debug/job-status');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/notebook/job-status returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/notebook/job-status');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/overview/kpis returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/overview/kpis');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/overview/sources returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/overview/sources');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/overview/activity returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/overview/activity');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/pipelines returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/pipelines');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/pipeline-view returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/pipeline-view');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/bronze-view returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/bronze-view');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/silver-view returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/silver-view');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/pipeline-executions returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/pipeline-executions');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/fabric-jobs returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/fabric-jobs');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/pipeline-activity-runs returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/pipeline-activity-runs');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/pipeline/run-snapshot returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/pipeline/run-snapshot');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/pipeline/failure-trace returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/pipeline/failure-trace');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/runner/sources returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/runner/sources');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/runner/entities returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/runner/entities');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/runner/state returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/runner/state');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/quality/scores returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/quality/scores');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/mdm/quality/scores returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/mdm/quality/scores');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/requests returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/requests');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/workspaces returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/workspaces');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/lakehouses returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/lakehouses');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/bronze-entities returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/bronze-entities');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/silver-entities returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/silver-entities');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/onboarding returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/onboarding');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/analyze-source returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/analyze-source');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/load-config returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/load-config');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/servers returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/servers');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/databases returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/databases');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/schemas returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/schemas');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/tables returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/tables');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/columns returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/columns');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/preview returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/preview');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/lakehouses returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/lakehouses');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/lakehouse-schemas returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/lakehouse-schemas');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/lakehouse-tables returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/lakehouse-tables');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/lakehouse-columns returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/lakehouse-columns');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/lakehouse-preview returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/lakehouse-preview');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/lakehouse-files returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/lakehouse-files');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/lakehouse-file-tables returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/lakehouse-file-tables');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/sql-explorer/lakehouse-file-detail returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sql-explorer/lakehouse-file-detail');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/audit/history returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/audit/history');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/audit/status returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/audit/status');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/test-swarm/runs returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/test-swarm/runs');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/test returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/test');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/crash returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/crash');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/search returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/search');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/cors-test returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/cors-test');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('GET /api/... returns 200 and valid JSON', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/...');
    expect(response.status()).toBe(200);
    const contentType = response.headers()['content-type'] || '';
    if (contentType.includes('application/json')) {
      const body = await response.json();
      expect(body).toBeDefined();
      if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
        if ('error' in body) expect(body.error).toBeFalsy();
      }
    } else {
      const text = await response.text();
      expect(text.length).toBeGreaterThan(0);
    }
  });
});

test.describe('API: Response time validation', () => {

  test('GET /api/things responds within 5 seconds', async ({ request }) => {
    const start = Date.now();
    const response = await request.get('http://localhost:8000/api/things');
    const elapsed = Date.now() - start;
    expect(response.status()).toBeLessThan(500);
    expect(elapsed).toBeLessThan(5000);
  });

  test('GET /api/health responds within 5 seconds', async ({ request }) => {
    const start = Date.now();
    const response = await request.get('http://localhost:8000/api/health');
    const elapsed = Date.now() - start;
    expect(response.status()).toBeLessThan(500);
    expect(elapsed).toBeLessThan(5000);
  });

  test('GET /api/admin/config responds within 5 seconds', async ({ request }) => {
    const start = Date.now();
    const response = await request.get('http://localhost:8000/api/admin/config');
    const elapsed = Date.now() - start;
    expect(response.status()).toBeLessThan(500);
    expect(elapsed).toBeLessThan(5000);
  });

  test('GET /api/fabric/workspaces responds within 5 seconds', async ({ request }) => {
    const start = Date.now();
    const response = await request.get('http://localhost:8000/api/fabric/workspaces');
    const elapsed = Date.now() - start;
    expect(response.status()).toBeLessThan(500);
    expect(elapsed).toBeLessThan(5000);
  });

  test('GET /api/fabric/connections responds within 5 seconds', async ({ request }) => {
    const start = Date.now();
    const response = await request.get('http://localhost:8000/api/fabric/connections');
    const elapsed = Date.now() - start;
    expect(response.status()).toBeLessThan(500);
    expect(elapsed).toBeLessThan(5000);
  });

  test('GET /api/fabric/security-groups responds within 5 seconds', async ({ request }) => {
    const start = Date.now();
    const response = await request.get('http://localhost:8000/api/fabric/security-groups');
    const elapsed = Date.now() - start;
    expect(response.status()).toBeLessThan(500);
    expect(elapsed).toBeLessThan(5000);
  });

  test('GET /api/setup/current-config responds within 5 seconds', async ({ request }) => {
    const start = Date.now();
    const response = await request.get('http://localhost:8000/api/setup/current-config');
    const elapsed = Date.now() - start;
    expect(response.status()).toBeLessThan(500);
    expect(elapsed).toBeLessThan(5000);
  });

  test('GET /api/alerts responds within 5 seconds', async ({ request }) => {
    const start = Date.now();
    const response = await request.get('http://localhost:8000/api/alerts');
    const elapsed = Date.now() - start;
    expect(response.status()).toBeLessThan(500);
    expect(elapsed).toBeLessThan(5000);
  });

  test('GET /api/classification/status responds within 5 seconds', async ({ request }) => {
    const start = Date.now();
    const response = await request.get('http://localhost:8000/api/classification/status');
    const elapsed = Date.now() - start;
    expect(response.status()).toBeLessThan(500);
    expect(elapsed).toBeLessThan(5000);
  });

  test('GET /api/classification/summary responds within 5 seconds', async ({ request }) => {
    const start = Date.now();
    const response = await request.get('http://localhost:8000/api/classification/summary');
    const elapsed = Date.now() - start;
    expect(response.status()).toBeLessThan(500);
    expect(elapsed).toBeLessThan(5000);
  });
});

test.describe('API: Parameterized endpoints (smoke)', () => {

  test('GET /api/data-manager/table/{name} responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/data-manager/table/1');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/db-explorer/table/{name} responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/db-explorer/table/1');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/db-explorer/table/{name}/schema responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/db-explorer/table/1/schema');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/glossary/entity/{entityId} responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/glossary/entity/1');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/lineage/columns/{entityId} responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/lineage/columns/1');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/mri/runs/{runId}/convergence responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/mri/runs/1/convergence');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/mri/runs/{runId}/visual-diffs responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/mri/runs/1/visual-diffs');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/mri/runs/{runId}/backend-results responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/mri/runs/1/backend-results');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/mri/runs/{runId}/ai-analyses responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/mri/runs/1/ai-analyses');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/mri/runs/{runId}/flake-results responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/mri/runs/1/flake-results');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/mri/runs/{runId}/iteration/{n} responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/mri/runs/1/iteration/1');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/quality/score/{entityId} responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/quality/score/1');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/sources/import/{job_id} responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/sources/import/1');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/audit/artifacts/{runId}/{testDir}/{fn} responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/audit/artifacts/1/1/1');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/test-swarm/runs/{runId}/convergence responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/test-swarm/runs/1/convergence');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/test-swarm/runs/{runId}/iteration/{n} responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/test-swarm/runs/1/iteration/1');
    expect([200, 404, 422]).toContain(response.status());
  });

  test('GET /api/entities/{id} responds (param substituted)', async ({ request }) => {
    const response = await request.get('http://localhost:8000/api/entities/1');
    expect([200, 404, 422]).toContain(response.status());
  });
});

test.describe('API: Mutation endpoints (existence check)', () => {

  test('POST /api/admin/auth endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/admin/auth', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/admin/config endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/admin/config', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/classification/scan endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/classification/scan', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/config-manager/update endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/config-manager/update', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/notebook-config/update endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/notebook-config/update', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/lakehouse-counts/scan endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/lakehouse-counts/scan', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/lakehouse-counts/refresh endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/lakehouse-counts/refresh', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/entity-status/sync endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/entity-status/sync', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/blender/query endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/blender/query', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('PUT /api/data-manager/table/{name}/{pk} — parameterized, skip', async () => {
    expect(true).toBe(true);
  });

  test('POST /api/db-explorer/query endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/db-explorer/query', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/engine/start endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/engine/start', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/engine/stop endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/engine/stop', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/engine/retry endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/engine/retry', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/engine/abort-run endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/engine/abort-run', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/engine/settings endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/engine/settings', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/engine/entity/{entity_id}/reset — parameterized, skip', async () => {
    expect(true).toBe(true);
  });

  test('POST /api/engine/optimize-all endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/engine/optimize-all', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/entities endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/entities', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('DELETE /api/entities/{entity_id} — parameterized, skip', async () => {
    expect(true).toBe(true);
  });

  test('POST /api/entities/bulk-delete endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/entities/bulk-delete', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/glossary/seed endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/glossary/seed', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/load-center/refresh endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/load-center/refresh', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/load-center/run endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/load-center/run', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/mri/run endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/mri/run', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/mri/baselines/accept-all endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/mri/baselines/accept-all', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/mri/baselines/{name} — parameterized, skip', async () => {
    expect(true).toBe(true);
  });

  test('POST /api/mri/api-tests/run endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/mri/api-tests/run', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/notebook-debug/run endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/notebook-debug/run', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/notebook/trigger endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/notebook/trigger', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/pipeline/trigger endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/pipeline/trigger', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/deploy-pipelines endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/deploy-pipelines', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/runner/prepare endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/runner/prepare', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/runner/trigger endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/runner/trigger', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/runner/restore endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/runner/restore', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/quality/refresh endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/quality/refresh', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/requests endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/requests', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('PATCH /api/requests/{id} — parameterized, skip', async () => {
    expect(true).toBe(true);
  });

  test('POST /api/datasources endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/datasources', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/onboarding endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/onboarding', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/onboarding/step endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/onboarding/step', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/onboarding/delete endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/onboarding/delete', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/sources/purge endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/sources/purge', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/sources/import endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/sources/import', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/source-tables endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/source-tables', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/register-bronze-silver endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/register-bronze-silver', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/source-manager/discover-all endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/source-manager/discover-all', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/load-config endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/load-config', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/sql-explorer/server-label endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/sql-explorer/server-label', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/audit/run endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/audit/run', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/fail endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/fail', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('POST /api/create endpoint exists (not 404)', async ({ request }) => {
    const response = await request.post('http://localhost:8000/api/create', {
      data: {},
    });
    expect(response.status()).not.toBe(404);
    expect(response.status()).toBeLessThan(500);
  });

  test('DELETE /api/items/{id} — parameterized, skip', async () => {
    expect(true).toBe(true);
  });
});

test.describe('API: Method validation', () => {

  test('DELETE /api/things is rejected', async ({ request }) => {
    const response = await request.delete('http://localhost:8000/api/things');
    expect([404, 405]).toContain(response.status());
  });

  test('DELETE /api/health is rejected', async ({ request }) => {
    const response = await request.delete('http://localhost:8000/api/health');
    expect([404, 405]).toContain(response.status());
  });

  test('DELETE /api/admin/config is rejected', async ({ request }) => {
    const response = await request.delete('http://localhost:8000/api/admin/config');
    expect([404, 405]).toContain(response.status());
  });

  test('DELETE /api/fabric/workspaces is rejected', async ({ request }) => {
    const response = await request.delete('http://localhost:8000/api/fabric/workspaces');
    expect([404, 405]).toContain(response.status());
  });

  test('DELETE /api/fabric/connections is rejected', async ({ request }) => {
    const response = await request.delete('http://localhost:8000/api/fabric/connections');
    expect([404, 405]).toContain(response.status());
  });
});
